// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_CZRTr9M7rIC2FgnHmOLOMmVVUHLDmoM',
    appId: '1:910914025100:web:c1df05a20ece8f495eada9',
    messagingSenderId: '910914025100',
    projectId: 'petsmatch-eb96d',
    authDomain: 'petsmatch-eb96d.firebaseapp.com',
    databaseURL:
        'https://petsmatch-eb96d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'petsmatch-eb96d.appspot.com',
    measurementId: 'G-EK70X4PVZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbhS2noQdmSZN6QnOsEjAN73uX5vjl6sI',
    appId: '1:910914025100:android:c5f292d63d8455805eada9',
    messagingSenderId: '910914025100',
    projectId: 'petsmatch-eb96d',
    databaseURL:
        'https://petsmatch-eb96d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'petsmatch-eb96d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLJ3f3cu2MChItj0H4un2pdl9o0kCb4QM',
    appId: '1:910914025100:ios:c05aac393ff6e3aa5eada9',
    messagingSenderId: '910914025100',
    projectId: 'petsmatch-eb96d',
    databaseURL:
        'https://petsmatch-eb96d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'petsmatch-eb96d.appspot.com',
    iosClientId:
        '910914025100-2454795sbn5fqlc2ccnlaujghaflofb0.apps.googleusercontent.com',
    iosBundleId: 'com.application.petsmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLJ3f3cu2MChItj0H4un2pdl9o0kCb4QM',
    appId: '1:910914025100:ios:c05aac393ff6e3aa5eada9',
    messagingSenderId: '910914025100',
    projectId: 'petsmatch-eb96d',
    databaseURL:
        'https://petsmatch-eb96d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'petsmatch-eb96d.appspot.com',
    iosClientId:
        '910914025100-2454795sbn5fqlc2ccnlaujghaflofb0.apps.googleusercontent.com',
    iosBundleId: 'com.application.petsmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_CZRTr9M7rIC2FgnHmOLOMmVVUHLDmoM',
    appId: '1:910914025100:web:2dca2c23a8a5360b5eada9',
    messagingSenderId: '910914025100',
    projectId: 'petsmatch-eb96d',
    authDomain: 'petsmatch-eb96d.firebaseapp.com',
    databaseURL:
        'https://petsmatch-eb96d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'petsmatch-eb96d.appspot.com',
    measurementId: 'G-3EEF309SWJ',
  );
}
